# Generated by Django 4.1 on 2022-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_contact_user_delete_article_delete_reporter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10000)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(name="Contact",),
        migrations.DeleteModel(name="User",),
    ]
