# Generated by Django 4.1 on 2022-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_categories_delete_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="categories", name="categories",),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(to="article.categories"),
        ),
    ]
