# Generated by Django 4.1 on 2022-08-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_remove_categories_categories_article_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories", old_name="Category", new_name="title",
        ),
    ]
