# Generated by Django 4.1 on 2022-08-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0008_user_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_article", old_name="user", new_name="user_linked",
        ),
    ]
