# Generated by Django 4.1 on 2022-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0009_rename_user_user_article_user_linked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_article", old_name="articles", new_name="articles_user",
        ),
        migrations.AddField(
            model_name="user_article",
            name="categories_user",
            field=models.ManyToManyField(to="article.categories"),
        ),
    ]
