# Generated by Django 4.1 on 2022-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_rename_articles_user_article_articles_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_article",
            name="articles_user",
            field=models.ManyToManyField(to="article.article"),
        ),
    ]
