# Generated by Django 4.1 on 2022-08-31 12:43

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0011_alter_user_article_articles_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_article",
            name="article_profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=article.models.filepath
            ),
        ),
    ]
