# Generated by Django 4.1 on 2022-08-31 19:37

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0012_user_article_article_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_article",
            name="article_profile_pic",
            field=models.ImageField(
                blank=True,
                default="default_imgs\\user-d-i.png",
                null=True,
                upload_to=article.models.filepath,
            ),
        ),
    ]
