# Generated by Django 4.1 on 2022-08-31 19:53

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0013_alter_user_article_article_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name="user_article",
            name="article_profile_pic",
            field=models.ImageField(
                blank=True,
                default="article\\default_imgs\\user-d-i.png",
                null=True,
                upload_to=article.models.filepath,
            ),
        ),
    ]
