# Generated by Django 4.1 on 2022-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0015_collection_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="articles",
            field=models.ManyToManyField(to="article.article"),
        ),
        migrations.AddField(
            model_name="collection",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to="article.user_article"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="admins",
            field=models.ManyToManyField(
                related_name="admins", to="article.user_article"
            ),
        ),
    ]
