# Generated by Django 4.1 on 2022-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0018_rename_collection_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="readers",
            field=models.ManyToManyField(
                related_name="readers", to="article.user_article"
            ),
        ),
    ]
